# Generated by Django 2.2.5 on 2020-05-10 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='collegeapp.Location'),
        ),
    ]
