# Generated by Django 2.2.5 on 2020-05-22 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0003_college_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='location',
            field=models.ForeignKey(default='Nepal', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='locn', to='collegeapp.Location'),
        ),
    ]
