# Generated by Django 2.2.5 on 2020-05-24 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0006_auto_20200522_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='location',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='location', to='collegeapp.Location'),
        ),
    ]
