# Generated by Django 2.2.5 on 2020-05-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0008_auto_20200528_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='affiliation',
            field=models.CharField(default='...', max_length=120),
        ),
        migrations.AlterField(
            model_name='college',
            name='Email',
            field=models.CharField(default='...', max_length=120),
        ),
        migrations.AlterField(
            model_name='college',
            name='Website',
            field=models.CharField(default='...', max_length=120),
        ),
        migrations.AlterField(
            model_name='college',
            name='address',
            field=models.CharField(default='...', max_length=120),
        ),
        migrations.AlterField(
            model_name='location',
            name='locationname',
            field=models.CharField(default='...', max_length=120, verbose_name='Location Name'),
        ),
    ]
